foodbrainers/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurants.urls')),
    # tutaj django wie, ze uzywamy templatu registration/login - w tym pliku nalezy umiescic template login,
    # ale mozna tez nadpisac uzywajac template_view, ale my mamy w folderze template login, ale nie mamy logout,
    # bo zrobilismy na logout przekierowanie na strone glowna
    path('accounts/login/',
         auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL,
                             document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.urls import path

from . import views

app_name = "restaurants"

urlpatterns = [
    path('', views.MainPage.as_view(), name='main'),
    path('all/', views.AllRestaurants.as_view(), name='all'),
    path('restaurants/<int:restaurant_id>',
         views.RestaurantDetails.as_view(), name='details'),
    path('add_to_card/<int:course_id>', views.add_to_card, name='add_to_card'),
    path('cart/', views.cart, name='cart'),
    path('create_order/', views.CreateOrder.as_view(), name='create_order'),
    path('signup/', views.signup, name='signup'),
]

# widok funkcyjny- funkcja ktora django wywoluje z parametrami, dlatego podajemy
# tylko referencje, a nie wywolujemy, w przypadku widokow klasowych  dodajemy asView(),
#  ktora przeksztalca klase w widok

restaurants/models.py
from django.db import models
from django.contrib.auth.models import User


class Cuisine(models.Model):
    name = models.CharField(max_length=20)
    # bedziemy widziec nasza kuchnie w panelu admina

    def __str__(self):
        return self.name


# w przypadku stringa nie pozwalamy na wartosc null przy liczbie mozemy podac null=True- baza danych zrozumie,
# ze jest mozliwosc podawania wartosci null
# musimy podac relacje do kuchni
class Restaurant(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    # dlugosc i szerokosc geograficzna
    latitude = models.FloatField()
    longitude = models.FloatField()
    # bedzie przechowywalo relacje do wielu kuchni
    # manyToMany - pole many to many fields,
    # pozwala nam przypisac kilka kuchni do restauracji i kilka restauracji do kuchni
    # trzymane jest to w tabeli pośredniczącej, łączącej ze sobą dane z dwóch modeli
    # gdybysmy chcieli zapisywac wiecej informacji w tej tabeli posredniczacej, tak jak w przypadku
    # orderEntry dodalismy quantity - kolumne dodatkowa - zeby to dodac musimy stworzyc sobie parametr
    # throught="nazwaKlasy", ktora sami musimy stworzyc
    cuisines = models.ManyToManyField(Cuisine)
    logo = models.ImageField(upload_to="logo", null=True, blank=True)
    opening_hours = models.CharField(max_length=20)
    min_order_amount = models.PositiveIntegerField(default=0)
    # delivery_cost -> calculable

    # menu = models.ManyToManyField(
    #     "Course", blank=True, related_name='restaurant_set')  # powstanie tu wirtualne pole restaurant_set

    # podajemy "" bo klasa Course jest tworzona pozniej -Django zrozumie go jak juz ten model bedzie dostepny

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.PositiveIntegerField()
    is_spicy = models.BooleanField()
    is_vegan = models.BooleanField()
    is_glutenfree = models.BooleanField()
    # related_name='courses')
    restaurant = models.ForeignKey(
        Restaurant, null=True,  on_delete=models.CASCADE, related_name='menu')

    def __str__(self):
        return self.name


class Order(models.Model):
    # relacja jeden do wielu bo jeden user moze zamowic kilka dan z roznych restauracji
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    courses = models.ManyToManyField(Course, through='OrderEntry')
    amount = models.PositiveIntegerField(default=0)
    delivery_cost = models.PositiveIntegerField(default=0)
    delivery = models.CharField(max_length=50)


# tabela posredniczaca - musimy miec dwa pola, ktore wskazuja na lewo i prawo czyli musimy miec oba pole
# miedzy ktorymi chcemy stworzyc dodatkowa relacje
# i to quantity w tym przypadku to bedzie dodatkowa kolumna ktora sobie stworzymy dla tej relacji
class OrderEntry(models.Model):
    # orderEntry posredniczy miedzy Order i Course
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

restaurants/forms.py
from django import forms
from .models import OrderEntry


class AddressForm(forms.Form):
    address = forms.CharField(
        max_length=100, widget=forms.TextInput(attrs={
            "placeholder": "Podaj swój adres"
        }))

# modelForm - tworzymy formularz na podstaiwe modelu i nie musimy definiowac wszystkich pol, mozemy to sobie uproscic


class OrderEntryForm(forms.ModelForm):
    class Meta:
        fields = ['course', 'quantity']
        model = OrderEntry

restaurants/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
# obiekt F sluzy do odwolywania sie do pol i do kolumn w zapytaniu, jest jeszcze obiekt Q
from django.forms import formset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, FormView
import googlemaps

from .forms import AddressForm, OrderEntryForm
from .models import Restaurant, Course, Order, OrderEntry


class MainPage(TemplateView):
    template_name = 'restaurants/main_page.html'
    extra_context = {
        'title': "Najlepsze jedzenie",
        'form': AddressForm(),
    }


class AllRestaurants(ListView):
    # context object name ustawia nam nazwe wynikow, pod ktora nazwa one trafiaja do templates
    context_object_name = 'restaurants'

    paginate_by = 4
    template_name = 'restaurants/all.html'

    def get_context_data(self, **kwargs):
        context = {
            'title': "Restauracje w Twojej okolicy",
            'address': self.address,
        }
        context.update(kwargs)
        return super().get_context_data(**context)

    def get_coordinates(self):
        client = googlemaps.Client(
            key=settings.GMAPS_KEY)
        geocode_results = client.geocode(self.address)
        if geocode_results:
            return (
                geocode_results[0]['geometry']['location']['lat'],
                geocode_results[0]['geometry']['location']['lng'],
            )
        return None, None
# adnotacja - dodaje wirtualna kolumne do naszego wyniku

    def get_queryset(self):

        qs = Restaurant.objects.all().prefetch_related(
            'cuisines')  # redukuje z n+1 do 1+1 -
        # zapytanie o restauracje i osobne zapytanie ktore pobiera nam wszystkie kuchnie

        if self.address:
            lat, lng = self.get_coordinates()
            if lat and lng:
                complex_F = (
                    (F('latitude') - lat) ** 2
                    +
                    (F('longitude') - lng) ** 2
                ) ** 0.5
                return qs.annotate(
                    distance=complex_F, delivery_cost=F('distance')*1000
                ).order_by('distance')
                Restaurant.objects.annotate(
                    distance=complex_F).order_by('distance')
        return qs

    def get_ordering(self):
        return self.request.GET.get('o', 'name')

    def get(self, request, *args, **kwargs):
        self.address = request.GET.get('address', '')
        return super().get(request, *args, **kwargs)


# pk_url_kwarg zbiera argumenty z url tutaj musimy je umiscic


class RestaurantDetails(DetailView):
    # w szablonie musze sie odwolywac do tego name i bedzie to moj obiekt
    context_object_name = "restaurant"
    pk_url_kwarg = 'restaurant_id'
    queryset = Restaurant.objects.all()
    template_name = 'restaurants/details.html'

    # self.object przechowuje OBIEKT sciagniety z bazy danych przez widok
    def get_context_data(self, **kwargs):
        context = {
            'title': self.object.name,
        }
        context.update(kwargs)
        return super().get_context_data(**context)

# sesja - cos w stylu slownika - dostep do tej sesji odbywa sie poprzez
# obiekt request request.session


def add_to_card(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    if 'cart' not in request.session:
        request.session['cart'] = list()
    # pk -primary_key to to samo co id, mozemy uzywac ich zamiennie,
    # id wystepuje w nazwie kolumny w bazie danych, ale django zpopularyzowal
    # pk
    request.session['cart'].append(course.pk)
    # tutaj musimy podac true zeby django wykrylo zmiane w obiekcie sesji
    request.session.modified = True
    messages.success(request, f'Dodano "{course}" do koszyka')

    if 'next' in request.GET:
        return redirect(request.GET['next'])
    return redirect('restaurants:all')


def cart(request):
    cart = []
    order_amount = 0
    if 'cart' in request.session:
        course_set = set(request.session['cart'])
        # wyciagamy wszystkie dania po id do tego sluzy to pk__in
        qs = Course.objects.filter(
            pk__in=course_set).select_related('restaurant')
        # n+1 zapytanie - zeby uniknac tego ze przy kazdej restauracji przechodzimy przez wszystkie dania przy zapytaniu,
        # ustawiamy joina, i wybieramy tylko to co nas interesuje - z relacji foreign_key pobiera nam obiekty,
        # zebysmy ich nie musieli pozyskiwac osobnymi zaputaniami

        for course in qs:
            x = request.session['cart'].count(
                course.pk)
            cart.append(
                {
                    # dajemy restaurant_set.first() -pierwsza opcja - bo danie tworzymy do restauracji a nie zeby jedno danie bylo w kilku restauracjach na raz
                    # to jest nasz foreign_key - dlatego wskazujemy ze ma szukac tylko po course.restaurant - dziala to tylko
                    # przy foreign_key , przy relacji M2M ustawiamy prefetch_related
                    'restaurant': course.restaurant,
                    'course': course,
                    'quantity': x,
                    'amount': x * course.price,
                }
            )
            order_amount += x * course.price
    context = {
        "title": "Koszyk",
        "cart": cart,
        'order_amount': order_amount,
    }
    return render(request, 'restaurants/cart.html', context)

# formset_factory - fabryka ktora generuje nam obiekty


class CreateOrder(LoginRequiredMixin, FormView):
    form_class = formset_factory(OrderEntryForm, extra=0)
    success_url = '/'
    template_name = 'restaurants/create_order.html'

    # metoda dispatch wczytuje sie na samym poczatku
    # i mozemy sobie tu pobierac dane ktore nam potrzebne z bazy danych, jak np ten adres
    def dispatch(self, request, *args, **kwargs):
        self.address = request.GET.get('address', '')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            'title': 'Złóż zamówienie',
            'address': self.address,
        }
        context.update(kwargs)
        return super().get_context_data(**context)

    def get_initial(self):
        cart = []
        if 'cart' in self.request.session:
            course_set = set(self.request.session['cart'])
            qs = Course.objects.filter(
                pk__in=course_set)

        for course in qs:
            x = self.request.session['cart'].count(
                course.pk)
            cart.append(
                {
                    'course': course,
                    'quantity': x,
                }
            )

        return cart

    def form_valid(self, form):
        # w cleaned_data jest przechowywana lista słowników z danymi z formularza
        order = Order(
            user=self.request.user,
            amount=sum([x['course'].price * x['quantity']
                        for x in form.cleaned_data]),
            delivery_cost=0,
            delivery=self.address,
        )
        order.save()
        order_entries = [
            OrderEntry(
                order=order, course=entry['course'], quantity=entry['quantity'])
            for entry in form.cleaned_data
        ]
        # zamiast n zapytan bulk tworzy nam jedno - bulk create - utworz wiele
        OrderEntry.objects.bulk_create(order_entries)
        messages.success(self.request, 'Złożono zamówienie')
        # czysci cala sesje- czyli caly slownik danego uzytkownika, zarazem wylogowyhe tez uzytkownika z sesji
        # self.request.session.flush()
        # w ten sposob usuniemy tylko koszyk:
        del self.request.session['cart']
        # lub funkcja clear() ktora czysci caly koszyk, ale nie wylogowuje
        return super().form_valid(form)


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('restaurants:main')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

templates/restaurants/all.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<main class="items">
    
    <section class="items_slider">
        <h3>W Twojej okolicy:</h3>
        <section class='items__group'>
        {% for restaurant in restaurants %}
            <a class='link' href="{% url 'restaurants:details' restaurant.id %}?address={{ address|urlencode }}">
                <div class="item">
                    <div class="logo"><img src="/media/{{restaurant.logo}}" alt="restaurant's logo">
                    </div>
                    <div class='desc'>
                        <div class="name">
                            <!-- <h4><a href="{% url 'restaurants:details' restaurant.id %}?address={{ address|urlencode }}">{{restaurant.name}}</a></h4> -->
                            <p class='p_name'>Kuchnia: {{ restaurant.cuisines.all|join:', ' }}</p>
                        </div>
                            <p class='half'>Minimalna kwota: <span>{{ restaurant.min_order_amount }} zł</span></p>
                            <p class='half'>Koszt dostawy: <span>{{ restaurant.delivery_cost|floatformat:0}} zł </span> </p>
                            <!-- <p>Odległość: {{ restaurant.distance }}</p> -->
                        <p class='opening_hours'>Zapraszamy: <p class='opening_hours'>{{ restaurant.opening_hours }}</p></p>
                        
                    </div>
                </div>
            </a>
        {% endfor %}
        </section>
        <section class='pagination'>
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                    <a class='first' href="?address={{address|urlencode}}&page=1">&laquo; first</a>
                    <a class='previous' href="?address={{address|urlencode}}&page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
        
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                    {% if page_obj.has_next %}
                    <a class='next' href="?address={{address|urlencode}}&page={{ page_obj.next_page_number }}">next</a>
                    <a class='last' href="?address={{address|urlencode}}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </section>
    </section>


</main>

<!-- <table>
    <tr>
        <th>
            Nazwa Restauracji
        </th>
        <th>
            Opis
        </th>
        <th>
            Współrzędne
        </th>
        <th>
            Odległość
        </th>
        <th>
            Kuchnia
        </th>
        <th>
            Godziny otwarcia
        </th>
        <th>
            Minimalna Kwota Zamówienia
        </th>
        <th>
            Koszt dostawy
        </th>
    </tr>
    {% for restaurant in restaurants %}
    <tr>
        <td>
            <a href="{% url 'restaurants:details' restaurant.id %}">{{restaurant.name}}</a>

        </td>
        <td>
            {{restaurant.description}}
        </td>
        <td>
            {{restaurant.latitude}},
            {{restaurant.longitude}}
        </td>
        <td>
            {{restaurant.cuisines.all|join:', '}}
        </td>
        <td>
            {{restaurant.opening_hours}}
        </td>
        <td>
            {{restaurant.min_order_amount}}
        </td>
        <td>
            {{ restaurant.min_order_amount}}
        </td>

    </tr>
    {% endfor %}
</table> -->

{% endblock %}

templates/restaurants/cart.html
{% extends "base.html" %}

{% block content %}
<section class='cart_container'>
<h3>Twoj koszyk</h3>

<table class='cart_table'>
    <tr>
        <th>Restauracja</th>
        <th>Danie</th>
        <th>Liczba</th>
        <th>Kwota</th>
    </tr>
    {% for entry in cart %}

    <tr>
        <td>{{ entry.restaurant }}</td>
        <td>{{ entry.course }}</td>
        <td>{{ entry.quantity }}</td>
        <td>{{ entry.amount }}</td>
    </tr>
    {% endfor %}
</table>
<h3>Suma: {{ order_amount }}</h3>
<a class='continue' href = "{% url 'restaurants:create_order'%}?address={{ address|urlencode }}">Złóż zamównienie</a>
<a class='continue' href='{% url "restaurants:all" %}?address={{ address|urlencode }}'>Kontynuuj zakupy</a>
</section>

<script>
    let message_ele = document.getElementsByClassName("success");
    setTimeout(function(){ 
        message_ele.style.display = "none"; 
        }, 5000);
    
</script>
{% endblock %}

templates/restaurants/create_order.html
{% extends "base.html" %}

{% block content %}
<section class='cart_container'>


<h3>Twoje zamównienie</h3>

<form class='form_create_order' method='POST' action="{% url 'restaurants:create_order' %}?address={{ address|urlencode }}">
    {% csrf_token %}
    <table class="order_table"> 
        {{ form.as_table }}
    </table>
    <input class="button" type='submit' value='Złóż zamówienie'>
</form>
</section>
{% endblock %}

templates/restaurants/details.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- # nazwa z kontekstu object_name -->
<div class="details_container">
    <div class='modal'>
        <section class='modal_courses'>
            <h3>{{ restaurant.name }}</h3>
            {% for course in restaurant.menu.all%}
                <div class ='course'>
                    <p class='course_name'>{{ course.name }}</p>
                    <p>{{ course.description }}</p>
                    <p class='price'>{{ course.price }}zł</p>
                    <div class='yes_no'>
                        <p>Pikantne?</p>
                        <p class='bool'>{{ course.is_spicy|yesno }}</p>
                        <p>Wegańskie?</p>
                        <p class='bool'>{{ course.is_vegan|yesno }}</p>
                        <p>Bezglutenowe?</p>
                        <p class='bool'>{{ course.is_glutenfree|yesno }}</p>
                        <!-- podajemy parametr next zeby nas przekierowalo, pobieramy cala sciezke przekazywana w url: 
                        -->
                        <a class='add' href='{% url "restaurants:add_to_card" course.pk %}?next={{ request.get_full_path }}'>Do koszyka</a>
                    </div>
                    
                </div>
            </a>
            {% endfor %}

            <!-- <table>
                <tr>
                    <th>Danie</th>
                    <th>Opis</th>
                    <th>Cena</th>
                    <th>Pikantne?</th>
                    <th>Wegańskie?</th>
                    <th>Bezglutenowe?</th>
                    <th>Zamówienie</th>
                </tr>
                bo many to many many relacje a restaurant.all jest managerem-->
                <!-- robimy nowe okienko z daniem -->
                <!-- {% for course in restaurant.menu.all%}
                <tr>
                    <td>{{ course.name }}</td>
                    <td>{{ course.description }}</td>
                    <td>{{ course.price }}</td>
                     to jest taki filt ktory z wartosci boolianowskiej zrobi nam tekst -->
                    <!-- <td>{{ course.is_spicy|yesno }}</td>
                    <td>{{ course.is_vegan|yesno }}</td>
                    <td>{{ course.is_glutenfree|yesno }}</td>
                    <td><a href='{% url "restaurants:add_to_card" course.pk %}?next={{ request.get_full_path }}'>Dodaj do koszyka</a></td>
                </tr>
                {% endfor %} -->
            <!-- </table> -->
        </section>    
        <section class='modal_location'>
            <h5> Jak nas znaleźć: </h5>
            <div id="map"></div>
            <p>{{ restaurant.latitude|json_script:"lat" }}</p>
            <p>{{ restaurant.longitude|json_script:"lng" }}</p>
            <!-- <h4> Kuchnia: </h4>
            <p>{{ restaurant.cuisines }}</p>
            <h5> Godziny otwarcia: </h5>
            <p>{{ restaurant.opening_hours }}</p>
            <h5> Minimalny koszt zamówienia: </h5>
            <p>{{ restaurant.min_order_amount }} zł</p> -->
            <!-- <h4> Menu: </h4>
            <div>{{ restaurant.menu }}</div> -->
        </section>  
    </div>
</div>

<script>
    let boolList = document.getElementsByClassName('bool');
    for (let i = 0, len = boolList.length; i < len; i++) {
        changeContent(boolList[i]);
    }
    function changeContent(element) {
        element.textContent === 'yes'? element.innerHTML = 'TAK': element.innerHTML = 'NIE';
    }

    initMap = () => {
        let latitude = JSON.parse(document.getElementById('lat').textContent);
        let longitude = JSON.parse(document.getElementById('lng').textContent);
        let location = { lat: latitude, lng: longitude }
        let itemMap = new google.maps.Map(document.getElementById('map'), {
            center: location,
            zoom: 15
        });
        let marker = new google.maps.Marker({ position: location, map: itemMap })
    };
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCBSDGXS3VSGw5883NK0Jola2YDel1L3tQ&callback=initMap">
</script>


{% endblock %}

templates/restaurants/main_page.html
{% extends "base.html" %}
{% load static%}
{% block content %}


<main class="main__main__page">

    <form method='GET' action="{% url 'restaurants:all' %}" enctype="multipart/form-data">
        <!--     <div class="inputs">
            <p>
                <label for="id_latitude"></label>
                <input type="number" name="latitude" class='main__input' value="50.05"
                    placeholder="szerokość geograficzna" id="id_latitude">
            </p>
            <p>
                 <label for="id_longitude">Longitude</label> 
                <input type="number" name="longitude" class='main__input' value="20.0"
                    placeholder="długość geograficzna" id="id_longitude">
            </p>
        </div> -->
        <div class="inputs">
            {{ form.address }}
        </div>
    </form>
</main>

{% endblock %}