foodbrainers/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurants.urls')),
    # tutaj django wie, ze uzywamy templatu registration/login - w tym pliku nalezy umiescic template login,
    # ale mozna tez nadpisac uzywajac template_view, ale my mamy w folderze template login, ale nie mamy logout,
    # bo zrobilismy na logout przekierowanie na strone glowna
    path('accounts/login/',
         auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL,
                             document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.urls import path

from . import views

app_name = "restaurants"

urlpatterns = [
    path('', views.MainPage.as_view(), name='main'),
    path('all/', views.AllRestaurants.as_view(), name='all'),
    path('restaurants/<int:restaurant_id>',
         views.RestaurantDetails.as_view(), name='details'),
    path('add_to_card/<int:course_id>', views.add_to_card, name='add_to_card'),
    path('cart/', views.cart, name='cart'),
    path('create_order/', views.CreateOrder.as_view(), name='create_order'),
    path('signup/', views.signup, name='signup'),
]

# widok funkcyjny- funkcja ktora django wywoluje z parametrami, dlatego podajemy
# tylko referencje, a nie wywolujemy, w przypadku widokow klasowych  dodajemy asView(),
#  ktora przeksztalca klase w widok

templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/style.css' %}">
    <!-- <script type="text/javascript" src="{% static 'restaurants/index.js' %}" async='async'></script> -->
    <title>FoodBrainers &bull; {{title}}</title>
</head>

<body>

    <main class='main'>
        <button class='hamburger nav'></button>
        <nav class='nav_main'>
            {% if user.is_authenticated %}
            <a href="{% url 'restaurants:main' %}"><p>Witaj, {{ user.username }}</p></a>
                <a href="{% url 'logout' %}">Wyloguj się</a>
            {% else %}
                <a href="{% url 'login' %}">Zaloguj się</a>
                {# <!-- <a href="{% url 'register' %}">Utwórz konto</a> --> #}
            {% endif %}
            <a href="{% url 'restaurants:cart' %}?address={{ address|urlencode }}"><span class='cart'>Koszyk: {{ request.session.cart|length }}</span></a>
        </nav>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <br>
      
        {% block content %} {% endblock %}
    </main>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;1,400;1,500&display=swap" rel="stylesheet">
</body>
<script>
    let hamburger = document.querySelector('.nav');
    let nav = document.querySelector('.nav_main');
    hamburger.addEventListener('click', (event)=>{
        event.preventDefault();
      hamburger.classList.toggle('active')
      nav.classList.toggle('active');
    })
    let message_ele = document.querySelector("li.success");
    setTimeout(function(){
        message_ele.style.display = "none";
    }, 3000)
</script> 
</html>